baseURL = "https://aisforairship.com"
languageCode = "en-us"
title = "A is for Airship"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "G-5HQ6HBDZYJ"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "[Andy Sayler](https://andysayler.com)"
  favicon = "favicon.ico"
  site_logo = ""
  description = "An Engineer's Blog"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/asayler/aisforairship/"
